/*
 * HLEDMATREX_Config.h
 *
 *  Created on:Sep 20, 2023
 *      Author: Muhammed Hesham
 */

#ifndef HLEDMATREX_CONFIG_H_
#define HLEDMATREX_CONFIG_H_

#define HLEDMAT_ROWS_PORT				MGPIO_PORTB
#define HLEDMAT_ROW0_PIN				MGPIO_PIN0
#define HLEDMAT_ROW1_PIN				MGPIO_PIN1
#define HLEDMAT_ROW2_PIN				MGPIO_PIN2
#define HLEDMAT_ROW3_PIN				MGPIO_PIN3

#define HLEDMAT_COLUMNS_PORT			MGPIO_PORTA
#define HLEDMAT_COL0_PIN				MGPIO_PIN0
#define HLEDMAT_COL1_PIN				MGPIO_PIN1
#define HLEDMAT_COL2_PIN				MGPIO_PIN2
#define HLEDMAT_COL3_PIN				MGPIO_PIN3
#define HLEDMAT_COL4_PIN				MGPIO_PIN4
#define HLEDMAT_COL5_PIN				MGPIO_PIN5
#define HLEDMAT_COL6_PIN				MGPIO_PIN6
#define HLEDMAT_COL7_PIN				MGPIO_PIN7


#endif
